/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aqsw_managment;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author p075446
 */
public class JFR_SQE_MainFrame extends javax.swing.JFrame {

    Statement stmt = null;
    AQSW_DB_Connexion aqswDBCON = new AQSW_DB_Connexion();
    ResultSet resultRequete_project;//contient la resultat de la requete excutée
    ResultSet resultRequete_ecu;//contient la resultat de la requete excutée
    ResultSet resultRequete_review;//contient la resultat de la requete excutée
    ResultSet resultRequete_requirement;
    ResultSet resultRequete_evidence;//contient les evidence pour une exigence donnee.
    ResultSet resultRequete_question;
    
    public JFR_SQE_MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_VehicleProjects = new javax.swing.JComboBox<>();
        jComboBox_ECU_List = new javax.swing.JComboBox<>();
        jBSelect = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel_UserName = new javax.swing.JLabel();
        jLabel_UserProfile = new javax.swing.JLabel();
        jLabel_UserName1 = new javax.swing.JLabel();
        jLabel_UserName2 = new javax.swing.JLabel();
        jLabel_UserName5 = new javax.swing.JLabel();
        jTxtUserName = new javax.swing.JTextField();
        jTxtProfile = new javax.swing.JTextField();
        jTxDate = new javax.swing.JTextField();
        jTxtVehicleProject = new javax.swing.JTextField();
        jTxtMilestone = new javax.swing.JTextField();
        jLabel_UserName4 = new javax.swing.JLabel();
        jTxtVehicleArchitecture = new javax.swing.JTextField();
        jLabel_UserName7 = new javax.swing.JLabel();
        jTxtProjectDecisionalStatus = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel_UserName11 = new javax.swing.JLabel();
        jTxtGate = new javax.swing.JTextField();
        jLabel_UserName3 = new javax.swing.JLabel();
        jTxtECUName = new javax.swing.JTextField();
        jLabel_UserName6 = new javax.swing.JLabel();
        jTxtSWVersion = new javax.swing.JTextField();
        jLabel_UserName8 = new javax.swing.JLabel();
        jTxtECUSupplier = new javax.swing.JTextField();
        jLabel_UserName14 = new javax.swing.JLabel();
        jTxtECUASIL = new javax.swing.JTextField();
        jLabel_UserName15 = new javax.swing.JLabel();
        jTxtSSRStatus = new javax.swing.JTextField();
        jTxtECUEQMSt = new javax.swing.JTextField();
        jLabel_UserName17 = new javax.swing.JLabel();
        jTxtECUDomaine = new javax.swing.JTextField();
        jLabel_UserName18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_ReviewList = new javax.swing.JComboBox<>();
        jBSelectReview = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRequirement = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEvidences = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableQuestion = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jComboBox_QUESTION_STATUS = new javax.swing.JComboBox<>();
        jBCommitQuestionReport = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaQuestionNotes = new javax.swing.JTextArea();
        jTextFieldSelectedQuestion_ID = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jComboBox_EVIDENCE_STATUS = new javax.swing.JComboBox<>();
        jBCommitEvidenceStatus = new javax.swing.JButton();
        jTSelected_Evidence_Id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "VEHICLE INFO SELECTION:"));

        jLabel1.setText("Select a Vehicle Project:");

        jLabel2.setText("Select a ECU:");

        jBSelect.setText("Select");
        jBSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_ECU_List, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_VehicleProjects, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jBSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox_VehicleProjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_ECU_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jBSelect)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Vehicle Project Informations:"));

        jLabel_UserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_UserName.setText("User Name");

        jLabel_UserProfile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_UserProfile.setText("Profile");

        jLabel_UserName1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_UserName1.setText("Date");

        jLabel_UserName2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_UserName2.setText("Vehicle Project");

        jLabel_UserName5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_UserName5.setText("Milestone");

        jTxtUserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTxtProfile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTxDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxDate.setMargin(new java.awt.Insets(2, 50, 2, 2));

        jTxtVehicleProject.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtVehicleProject.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTxtMilestone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtMilestone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_UserName4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_UserName4.setText("Architecture");

        jTxtVehicleArchitecture.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtVehicleArchitecture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_UserName7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_UserName7.setText("Decisional Status");

        jTxtProjectDecisionalStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtProjectDecisionalStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_UserName7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_UserName4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_UserName5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_UserName2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_UserName1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_UserProfile, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_UserName, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtProjectDecisionalStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtVehicleArchitecture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMilestone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtVehicleProject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtUserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_UserName)
                    .addComponent(jTxtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_UserProfile))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_UserName1)
                    .addComponent(jTxDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_UserName2)
                    .addComponent(jTxtVehicleProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtMilestone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_UserName5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_UserName4)
                    .addComponent(jTxtVehicleArchitecture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_UserName7)
                    .addComponent(jTxtProjectDecisionalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("AQSW APPLICATION TOOL - SQE DASHBOARD");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSeparator1.setBackground(new java.awt.Color(255, 153, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 153, 0));
        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jSeparator2.setBackground(new java.awt.Color(255, 153, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 153, 0));
        jSeparator2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel4.setBackground(new java.awt.Color(0, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "ECU Informations Data"));

        jLabel_UserName11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_UserName11.setText("Gate");

        jTxtGate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtGate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_UserName3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_UserName3.setText("ECU Name");

        jTxtECUName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtECUName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_UserName6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_UserName6.setText("SW Version");

        jTxtSWVersion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtSWVersion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_UserName8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_UserName8.setText("ECU Supplier");

        jTxtECUSupplier.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtECUSupplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_UserName14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_UserName14.setText("ASIL");

        jTxtECUASIL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtECUASIL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_UserName15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_UserName15.setText("SSR Status");

        jTxtSSRStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtSSRStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTxtECUEQMSt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtECUEQMSt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_UserName17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_UserName17.setText("EQM Decisional Status");

        jTxtECUDomaine.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtECUDomaine.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_UserName18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_UserName18.setText("Domaine");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_UserName17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_UserName15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_UserName18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_UserName14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_UserName11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_UserName8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_UserName6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_UserName3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtECUEQMSt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtSSRStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtECUDomaine, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtECUASIL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtGate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtECUSupplier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtSWVersion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtECUName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_UserName3)
                    .addComponent(jTxtECUName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtSWVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_UserName6))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtECUSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_UserName8))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtGate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_UserName11))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtECUASIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_UserName14))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtECUDomaine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_UserName18))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtSSRStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_UserName15))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtECUEQMSt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_UserName17))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "REVIEW SELECTION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel3.setText("Select review");

        jBSelectReview.setText("Select Review");
        jBSelectReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSelectReviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox_ReviewList, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jBSelectReview, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox_ReviewList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBSelectReview)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableRequirement.setBackground(new java.awt.Color(255, 204, 204));
        jTableRequirement.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jTableRequirement.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTableRequirement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FULL NAME", "VERSION TYPE", "TYPE", "DOMAINE", "ASIL", "SCM STATUS", "RESPONSIBLE", "OUTCOME"
            }
        ));
        jTableRequirement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRequirementMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableRequirement);

        jTableEvidences.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jTableEvidences.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EVIDENCE ID", "TITLE", "STATUS"
            }
        ));
        jTableEvidences.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEvidencesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableEvidences);

        jTableQuestion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jTableQuestion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "QUESTION ID", "QUESTION FULL NAME", "QUESTION NOTES", "QUESTION STATUS"
            }
        ));
        jTableQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableQuestionMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableQuestion);

        jPanel6.setBackground(new java.awt.Color(255, 255, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "UPDATING QUESTION DATAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jComboBox_QUESTION_STATUS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FS", "PS", "NS", "NI", "NA", "DE", "TR", "NR" }));

        jBCommitQuestionReport.setText("Commit ");
        jBCommitQuestionReport.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBCommitQuestionReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCommitQuestionReportActionPerformed(evt);
            }
        });

        jLabel4.setText("Selected Question ID");

        jTextAreaQuestionNotes.setColumns(20);
        jTextAreaQuestionNotes.setRows(5);
        jScrollPane4.setViewportView(jTextAreaQuestionNotes);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(57, 57, 57)
                            .addComponent(jTextFieldSelectedQuestion_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jBCommitQuestionReport, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox_QUESTION_STATUS, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldSelectedQuestion_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_QUESTION_STATUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBCommitQuestionReport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "UPDATING DATAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jComboBox_EVIDENCE_STATUS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delivered", "Not Delivered", "Partially Delivered" }));

        jBCommitEvidenceStatus.setText("Commit ");
        jBCommitEvidenceStatus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBCommitEvidenceStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCommitEvidenceStatusActionPerformed(evt);
            }
        });

        jLabel5.setText("Selected Evidence ID");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox_EVIDENCE_STATUS, 0, 165, Short.MAX_VALUE)
                        .addComponent(jTSelected_Evidence_Id)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCommitEvidenceStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTSelected_Evidence_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox_EVIDENCE_STATUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jBCommitEvidenceStatus)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel6))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1))))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(289, 289, 289))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel7, jScrollPane2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
       // jLabel_UserName.setText(string);
       // jLabel_UserProfile.setText(string);
       String requetteSQL_SELECT_ALL_PROJECT_NAME = "select project_name from tproject;";
       String requetteSQL_SELECT_ALL_ECU_NAME = "select ecu_name from tecu;";
       String requeteSQL_SELECT_ALL_REVIEW = "SELECT review_name from treview;";
       
       
       //// Initiation de la combo Project 
       try {
           stmt = aqswDBCON.getCon().createStatement();
           resultRequete_project = stmt.executeQuery(requetteSQL_SELECT_ALL_PROJECT_NAME);
            while(resultRequete_project.next())
                {
                /** on insere dans la ComboBox */
                jComboBox_VehicleProjects.addItem(resultRequete_project.getString("project_name"));
                } 
            resultRequete_project.close();
            } 
       catch (SQLException ex) 
            {
            System.out.println(ex);
            } 
       //// Initiation de la combo Review 
       try {
           stmt = aqswDBCON.getCon().createStatement();
           resultRequete_review = stmt.executeQuery(requeteSQL_SELECT_ALL_REVIEW);
            while(resultRequete_review.next())
                {
                /** on insere dans la ComboBox */
                jComboBox_ReviewList.addItem(resultRequete_review.getString("review_name"));
                } 
            resultRequete_review.close();
            } 
       catch (SQLException ex) 
            {
            System.out.println(ex);
            } 
       // Initiation de la combo ECU
       try {
           stmt = aqswDBCON.getCon().createStatement();
           resultRequete_ecu = stmt.executeQuery(requetteSQL_SELECT_ALL_ECU_NAME);
            while(resultRequete_ecu.next())
                {
                /** on insere dans la ComboBox */
                jComboBox_ECU_List.addItem(resultRequete_ecu.getString("ecu_name"));
                } 
            stmt.close();
            resultRequete_ecu.close();
            } 
       catch (SQLException ex) 
            {
            System.out.println(ex);
            } 
       
           
       
     // mettre la date du jour
        //aqswDBCON.con.close();
        
    }//GEN-LAST:event_formWindowActivated

    public ArrayList<tRequirement> getRequirementData(String selectedRev){
        
        ArrayList<tRequirement> reqData = new ArrayList<>();
        System.out.println("pass2");
        System.out.println(selectedRev);
        String requeteSQL_SELECT_REVIEW_ID = "select * from treview WHERE review_name = '"+selectedRev+"';";
        int selected_review_id = 0;
        int line=0;
         try
        {
            stmt = aqswDBCON.getCon().createStatement();
            resultRequete_review = stmt.executeQuery(requeteSQL_SELECT_REVIEW_ID);
            while (resultRequete_review.next()) 
                {
                    selected_review_id = resultRequete_review.getInt("review_id");
                   
                }
            resultRequete_review.close();
            
        }
        catch(SQLException ex){
        }
        System.out.println("pass2.5");
        System.out.println(selected_review_id);
        String requetteSQL_SELECT_TREQ = "select * from trequirement WHERE fk_requirement_review_id = '"+selected_review_id+"';"; 
        try
        {
            stmt = aqswDBCON.getCon().createStatement();
            resultRequete_review = stmt.executeQuery(requetteSQL_SELECT_TREQ);
            
            tRequirement req; //declaration objet de type tRequirement
            while(resultRequete_review.next())
            {
                //RecordList(int id,int mil, float vol, String recDate, float pr, String dt)
                String req_id = resultRequete_review.getString("requirement_id");
                System.out.println("pass2.6");
        System.out.println(req_id);
                String req_title = resultRequete_review.getString("requirement_title");
                System.out.println("pass2.7");
        System.out.println(req_title);
                String req_ver_type = resultRequete_review.getString("requirement_version_type");
                String req_type = resultRequete_review.getString("requirement_type");
                String req_dom = resultRequete_review.getString("requirement_domaine");
                String req_asil = resultRequete_review.getString("requirement_asil_level");
                String req_scm_st = resultRequete_review.getString("requirement_scm_status");
                String req_rep = resultRequete_review.getString("requirement_responsible");
                String fk_req_outcome = resultRequete_review.getString("fk_requirement_outcome_id");
                
                req = new tRequirement(req_id,req_title,req_ver_type,req_type,req_dom,req_asil,req_scm_st,req_rep,fk_req_outcome);
                //recL = new RecordList();
                reqData.add(req);
                line++;    
            }
            System.out.println("nombre de lignes");
        System.out.println(line);
        }
        catch(SQLException ex){
        }
            
        
        return reqData;
    }
    
    public void displayRequirementInJTable(String selRev){
    
        ArrayList<tRequirement> myReqlist = getRequirementData(selRev);
        // refresh data table
        System.out.println("pass3");
        System.out.println(selRev);
        DefaultTableModel model = (DefaultTableModel) jTableRequirement.getModel();
        Object[] row = new Object[9];
        
        for (int i=0; i< myReqlist.size();i++)
        {
            row[0] = myReqlist.get(i).get_requirement_Id();
            row[1] = myReqlist.get(i).get_requirement_Title();
            row[2] = myReqlist.get(i).get_requirement_Version_Type();
            row[3] = myReqlist.get(i).get_requirement_Type();
            row[4] = myReqlist.get(i).get_requirement_Domaine();
            row[5] = myReqlist.get(i).get_requirement_ASIL_Level();
            row[6] = myReqlist.get(i).get_requirement_SCM_Status();
            row[7] = myReqlist.get(i).get_requirement_Responsible();
            row[8] = myReqlist.get(i).get_fk_requirement_outcome_id();
            model.addRow(row);
        }
    }
    
    private void jBSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSelectActionPerformed
       
        String today = aujourdhui();
        String selectedvehicleproject;
        String selectedecu;
        
        
        selectedvehicleproject = jComboBox_VehicleProjects.getSelectedItem().toString();
        selectedecu = jComboBox_ECU_List.getSelectedItem().toString();
        
        
        String requeteSQL_SELECT_FROM_PROJECT_NAME = "SELECT * FROM tproject WHERE project_name = '"+selectedvehicleproject+"';";
        String requeteSQL_SELECT_FROM_ECU_NAME = "SELECT *from tecu WHERE ecu_name = '"+selectedecu+"';";
        
        jTxDate.setText(today);
        
        
        jTxtVehicleProject.setText(selectedvehicleproject);
        jTxtECUName.setText(selectedecu);
        
        //------------ info projet -----------------
         try
        {
            stmt = aqswDBCON.getCon().createStatement();
            resultRequete_project = stmt.executeQuery(requeteSQL_SELECT_FROM_PROJECT_NAME);
            while (resultRequete_project.next()) 
                {
                    String selected_prj_archi = resultRequete_project.getString("project_architecture");
                    String selected_prj_dec_st = resultRequete_project.getString("project_decisional_status");
                    String selected_prj_milestone = resultRequete_project.getString("project_relatedMilestone") ; 
                    jTxtVehicleArchitecture.setText(selected_prj_archi);
                    jTxtProjectDecisionalStatus.setText(selected_prj_dec_st);
                    jTxtMilestone.setText(selected_prj_milestone);
                }
            
            
        }
        catch(SQLException ex){
        }
        //------------ info ECU -----------------
         try
        {
            stmt = aqswDBCON.getCon().createStatement();
            resultRequete_ecu = stmt.executeQuery(requeteSQL_SELECT_FROM_ECU_NAME);
            while (resultRequete_ecu.next()) 
                {
                    String ecu_supp_name = resultRequete_ecu.getString("ecu_supplier_name");
                    String ecu_asil = resultRequete_ecu.getString("ecu_asil_level");
                    String ecu_ssr_st = resultRequete_ecu.getString("ecu_ssr_status");
                    String ecu_eqm_st = resultRequete_ecu.getString("ecu_eqm_decisional_status");
                    String ecu_domaine = resultRequete_ecu.getString("ecu_domaine");
                    jTxtECUSupplier.setText(ecu_supp_name);
                    jTxtSWVersion.setText("to be added");
                    jTxtGate.setText("to be added");
                    jTxtECUASIL.setText(ecu_asil);
                    jTxtMilestone.setText("to be added");
                    jTxtSSRStatus.setText(ecu_ssr_st);
                    jTxtECUEQMSt.setText(ecu_eqm_st);
                    jTxtECUDomaine.setText(ecu_domaine);
                }
            
         stmt.close();
         resultRequete_ecu.close();
        }
        catch(SQLException ex){
        }
        
        
    }//GEN-LAST:event_jBSelectActionPerformed

    private void jBSelectReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSelectReviewActionPerformed
        
        String selectedReview = jComboBox_ReviewList.getSelectedItem().toString();
        // refresh data table
        System.out.println("dans fonction jBSelectReviewActionPerformed");
        System.out.println(selectedReview);
        DefaultTableModel model = (DefaultTableModel) jTableRequirement.getModel();
        model.setRowCount(0);
        
        // affichage des resultats dans une table
        displayRequirementInJTable(selectedReview);
    }//GEN-LAST:event_jBSelectReviewActionPerformed

    public ArrayList<tEvidence> getEvidenceData(String selectedReq){
        
        ArrayList<tEvidence> evidData = new ArrayList<>();
        System.out.println("Evidence dans getEvidenceData");
        System.out.println(selectedReq);
        String requeteSQL_SELECT_EVIDENCE = "select pk_trequirement_requirement_id,evidence_id,evidence_title,evidence_status\n" +
                                            "from trequirement_tevidence RE, tevidence E\n" +
                                            "where RE.pk_trequirement_requirement_id = '"+selectedReq+"' AND\n" +
                                            "E.evidence_id = RE.pk_tevidence_evidence_id";
        
        int line=0;
        try
        {
            stmt = aqswDBCON.getCon().createStatement();
            resultRequete_evidence = stmt.executeQuery(requeteSQL_SELECT_EVIDENCE);
            
            tEvidence evidence; //declaration objet de type tRequirement
            while(resultRequete_evidence.next())
            {
                //RecordList(int id,int mil, float vol, String recDate, float pr, String dt)
                String evid_id = resultRequete_evidence.getString("evidence_id");
                String evid_title = resultRequete_evidence.getString("evidence_title");
                String evid_ver_type = resultRequete_evidence.getString("evidence_status");
                evidence = new tEvidence(evid_id,evid_title,evid_ver_type);               
                evidData.add(evidence);
                line++;    
            }
        System.out.println("Evidence dans getEvidenceData : nombre de lignes");
        System.out.println(line);
        stmt.close();
        resultRequete_evidence.close();
        }
        catch(SQLException ex){
        }            
        return evidData;
    }
    private void displayEvidenceInTable(String reqId)
    {
        ArrayList<tEvidence> myEvidlist = getEvidenceData(reqId);
        // refresh data table
        System.out.println("pass6");
        System.out.println(reqId);
        DefaultTableModel model = (DefaultTableModel) jTableEvidences.getModel();
        model.setRowCount(0);
        Object[] row = new Object[3];
        
        for (int i=0; i< myEvidlist.size();i++)
        {
            row[0] = myEvidlist.get(i).get_evidence_Id();
            row[1] = myEvidlist.get(i).get_evidence_Title();
            row[2] = myEvidlist.get(i).get_evidence_Status();
            model.addRow(row);
        }
        
    }
    private void jTableRequirementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRequirementMouseClicked
        
        int i = jTableRequirement.getSelectedRow();
        TableModel model =  jTableRequirement.getModel();   
        
        String req_id = model.getValueAt(i, 0).toString();
        
        displayEvidenceInTable(req_id);
    }//GEN-LAST:event_jTableRequirementMouseClicked

    public ArrayList<Tquestion_DB> getQuestionData(String selectedEvid){
        
        ArrayList<Tquestion_DB> questionData = new ArrayList<>();
        System.out.println("Question dans getQuestionData");
        System.out.println(selectedEvid);
        String requeteSQL_SELECT_EVIDENCE = "SELECT question_id, question_full_question, question_notes, question_status\n" +
        "FROM public.tquestion\n" +
        "where fk_question_evidence_id = '"+selectedEvid+"';";
        
        int line=0;
        try
        {
            stmt = aqswDBCON.getCon().createStatement();
            resultRequete_question = stmt.executeQuery(requeteSQL_SELECT_EVIDENCE);
            
            Tquestion_DB question; //declaration objet de type tRequirement
            while(resultRequete_question.next())
            {
                //RecordList(int id,int mil, float vol, String recDate, float pr, String dt)
                String quest_id = resultRequete_question.getString("question_id");
                String quest_full_name = resultRequete_question.getString("question_full_question");
                String quest_note = resultRequete_question.getString("question_notes");
                String quest_st = resultRequete_question.getString("question_status");
                question = new Tquestion_DB(quest_id,quest_full_name,quest_note,quest_st);               
                questionData.add(question);
                line++;    
            }
        System.out.println("Evidence dans getQuestionData : nombre de lignes");
        System.out.println(line);
        stmt.close();
        resultRequete_question.close();
        }
        catch(SQLException ex){
        }            
        return questionData;
    }
    
    private void displayQuestionInTable(String evidId)
    {
        ArrayList<Tquestion_DB> myQuestionlist = getQuestionData(evidId);
        // refresh data table
        System.out.println("dans fonction displayQuestionInTable ");
        System.out.println(evidId);
        DefaultTableModel model = (DefaultTableModel) jTableQuestion.getModel();
        model.setRowCount(0);
        Object[] row = new Object[4];
        
        for (int i=0; i< myQuestionlist.size();i++)
        {
            row[0] = myQuestionlist.get(i).getQuestionId();
            row[1] = myQuestionlist.get(i).getQuestionFullQuestion();
            row[2] = myQuestionlist.get(i).getQuestionNotes();
            row[3] = myQuestionlist.get(i).getQuestionStatus();
            model.addRow(row);
        }
        
    }
    private void jTableEvidencesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEvidencesMouseClicked
        
        int i = jTableEvidences.getSelectedRow();
        TableModel model =  jTableEvidences.getModel();   
        
        String evid_id = model.getValueAt(i, 0).toString();
        jTSelected_Evidence_Id.setText(evid_id);
        displayQuestionInTable(evid_id);
    }//GEN-LAST:event_jTableEvidencesMouseClicked

    private void jBCommitQuestionReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCommitQuestionReportActionPerformed
        
        String question_st = jComboBox_QUESTION_STATUS.getSelectedItem().toString();
        String question_selected = jTextFieldSelectedQuestion_ID.getText();
        String question_note = jTextAreaQuestionNotes.getText();
        String requetSQL_UPDATE_QUESTION_ST = "UPDATE public.tquestion\n" +
                                                "SET question_status = '"+question_st+"', question_notes = '"+question_note+"'\n" +
                                                "WHERE question_id = '"+question_selected+"';";
        
        try
        {
            stmt = aqswDBCON.getCon().createStatement();
            stmt.executeUpdate(requetSQL_UPDATE_QUESTION_ST);
            JOptionPane.showMessageDialog(null, "MAJ Question DATA dans la BDD execute avec succes");
            stmt.close();
        }
        catch(SQLException ex){
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_jBCommitQuestionReportActionPerformed

    private void jBCommitEvidenceStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCommitEvidenceStatusActionPerformed
        //get status value from combobox
        String evid_st = jComboBox_EVIDENCE_STATUS.getSelectedItem().toString();
        String evid_selected = jTSelected_Evidence_Id.getText();
        String requetSQL_UPDATE_EVIDENCE_ST = "UPDATE public.tevidence\n" +
                                                "SET evidence_status = '"+evid_st+"'\n" +
                                                "WHERE evidence_id = '"+evid_selected+"';";
        
        try
        {
            stmt = aqswDBCON.getCon().createStatement();
            stmt.executeUpdate(requetSQL_UPDATE_EVIDENCE_ST);
            JOptionPane.showMessageDialog(null, "MAJ Status dans la BDD execute avec succes");
            stmt.close();
        }
        catch(SQLException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jBCommitEvidenceStatusActionPerformed

    private void jTableQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableQuestionMouseClicked

    int i = jTableQuestion.getSelectedRow();
        TableModel model =  jTableQuestion.getModel();   
        
        String question_id = model.getValueAt(i, 0).toString();
        System.out.println("apres le click de la sourie");
        System.out.println(question_id);
        String question_note = model.getValueAt(i, 1).toString();
        jTextFieldSelectedQuestion_ID.setText(question_id);
        jTextAreaQuestionNotes.setText(question_note);
        
    }//GEN-LAST:event_jTableQuestionMouseClicked

    public String aujourdhui() {
     return LocalDate.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy"));
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFR_SQE_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFR_SQE_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFR_SQE_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFR_SQE_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFR_SQE_MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCommitEvidenceStatus;
    private javax.swing.JButton jBCommitQuestionReport;
    private javax.swing.JButton jBSelect;
    private javax.swing.JButton jBSelectReview;
    private javax.swing.JComboBox<String> jComboBox_ECU_List;
    private javax.swing.JComboBox<String> jComboBox_EVIDENCE_STATUS;
    private javax.swing.JComboBox<String> jComboBox_QUESTION_STATUS;
    private javax.swing.JComboBox<String> jComboBox_ReviewList;
    private javax.swing.JComboBox<String> jComboBox_VehicleProjects;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_UserName;
    private javax.swing.JLabel jLabel_UserName1;
    private javax.swing.JLabel jLabel_UserName11;
    private javax.swing.JLabel jLabel_UserName14;
    private javax.swing.JLabel jLabel_UserName15;
    private javax.swing.JLabel jLabel_UserName17;
    private javax.swing.JLabel jLabel_UserName18;
    private javax.swing.JLabel jLabel_UserName2;
    private javax.swing.JLabel jLabel_UserName3;
    private javax.swing.JLabel jLabel_UserName4;
    private javax.swing.JLabel jLabel_UserName5;
    private javax.swing.JLabel jLabel_UserName6;
    private javax.swing.JLabel jLabel_UserName7;
    private javax.swing.JLabel jLabel_UserName8;
    private javax.swing.JLabel jLabel_UserProfile;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTSelected_Evidence_Id;
    private javax.swing.JTable jTableEvidences;
    private javax.swing.JTable jTableQuestion;
    private javax.swing.JTable jTableRequirement;
    private javax.swing.JTextArea jTextAreaQuestionNotes;
    private javax.swing.JTextField jTextFieldSelectedQuestion_ID;
    private javax.swing.JTextField jTxDate;
    private javax.swing.JTextField jTxtECUASIL;
    private javax.swing.JTextField jTxtECUDomaine;
    private javax.swing.JTextField jTxtECUEQMSt;
    private javax.swing.JTextField jTxtECUName;
    private javax.swing.JTextField jTxtECUSupplier;
    private javax.swing.JTextField jTxtGate;
    private javax.swing.JTextField jTxtMilestone;
    private javax.swing.JTextField jTxtProfile;
    private javax.swing.JTextField jTxtProjectDecisionalStatus;
    private javax.swing.JTextField jTxtSSRStatus;
    private javax.swing.JTextField jTxtSWVersion;
    private javax.swing.JTextField jTxtUserName;
    private javax.swing.JTextField jTxtVehicleArchitecture;
    private javax.swing.JTextField jTxtVehicleProject;
    // End of variables declaration//GEN-END:variables
}
