/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aqsw_managment;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author p075446
 */
public class JFR_IST_MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFR_IST_MainFrame
     */
    Statement stmt = null;
    AQSW_DB_Connexion aqswDBCON = new AQSW_DB_Connexion();
    ResultSet resultRequete_project;//contient la resultat de la requete excutée
    ResultSet resultRequete_ecu;
    ResultSet resultRequete_dt;
   
    int dtN;
    
    public JFR_IST_MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar_IST_MainFrame = new javax.swing.JToolBar();
        jComboBox_ProjectList_FromDB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jBAddECU = new javax.swing.JButton();
        jComboBoxECUName_fromDB = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTSupplierName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTHWCOCA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTSWCOCA = new javax.swing.JTextField();
        jComboBoxASILLevel = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTSWNETWORK = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTSQA = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTBOXType = new javax.swing.JTextField();
        jTECUDomaine = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTECUFullName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableECUADDED = new javax.swing.JTable();
        jBCommitECUIntoDB = new javax.swing.JButton();
        jTVehicleID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jBShowPrjID = new javax.swing.JButton();
        jBCloseWindow = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTDTName = new javax.swing.JTextField();
        jBAddDT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jToolBar_IST_MainFrame.setRollover(true);

        jComboBox_ProjectList_FromDB.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jComboBox_ProjectList_FromDBMouseWheelMoved(evt);
            }
        });
        jComboBox_ProjectList_FromDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_ProjectList_FromDBMouseClicked(evt);
            }
        });
        jComboBox_ProjectList_FromDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ProjectList_FromDBActionPerformed(evt);
            }
        });

        jLabel1.setText("Vehicle name");

        jLabel2.setText("ECU name");

        jBAddECU.setBackground(new java.awt.Color(0, 255, 204));
        jBAddECU.setText("ADD ECU TO LIST");
        jBAddECU.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBAddECU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddECUActionPerformed(evt);
            }
        });

        jLabel3.setText("ECU Supplier Name");

        jLabel4.setText("ASIL LEVEL");

        jLabel5.setText("HW COCA");

        jLabel6.setText("SW COCA");

        jComboBoxASILLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "QM", "A", "B", "C", "D" }));

        jLabel8.setText("NETWORK");

        jLabel9.setText("SQA");

        jLabel10.setText("DOMAINE");

        jLabel11.setText("BOX TYPE");

        jLabel12.setText("ECU FULL NAME");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jTableECUADDED.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DT NAME", "NAME", "FULL NAME", "SUPPLIER NAME", "ASIL", "DOMAINE", "BOX TYPE"
            }
        ));
        jScrollPane1.setViewportView(jTableECUADDED);

        jBCommitECUIntoDB.setBackground(new java.awt.Color(0, 255, 204));
        jBCommitECUIntoDB.setText("COMMIT");
        jBCommitECUIntoDB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBCommitECUIntoDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCommitECUIntoDBActionPerformed(evt);
            }
        });

        jLabel7.setText("Vehicle ID");

        jBShowPrjID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBShowPrjID.setText("-->");
        jBShowPrjID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBShowPrjIDActionPerformed(evt);
            }
        });

        jBCloseWindow.setText("CLOSE");
        jBCloseWindow.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBCloseWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCloseWindowActionPerformed(evt);
            }
        });

        jLabel13.setText("DT Name");

        jBAddDT.setBackground(new java.awt.Color(0, 255, 204));
        jBAddDT.setText("ADD DT");
        jBAddDT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBAddDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddDTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(93, 93, 93)
                                    .addComponent(jComboBox_ProjectList_FromDB, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(jBShowPrjID)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTVehicleID, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jBAddDT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jBAddECU, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTBOXType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTECUDomaine, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBoxASILLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTHWCOCA, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTSWCOCA, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTSWNETWORK, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTSQA, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTECUFullName))
                                        .addComponent(jSeparator2)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTDTName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jComboBoxECUName_fromDB, 0, 126, Short.MAX_VALUE)
                                                    .addComponent(jTSupplierName)))))
                                    .addGap(26, 26, 26)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jBCommitECUIntoDB, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1177, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jToolBar_IST_MainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBCloseWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(265, 265, 265)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1581, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar_IST_MainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jBCloseWindow)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox_ProjectList_FromDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTVehicleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jBShowPrjID))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTDTName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxECUName_fromDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTECUFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxASILLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTHWCOCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTSWCOCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTSWNETWORK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTSQA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTECUDomaine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTBOXType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBAddECU)
                        .addComponent(jBCommitECUIntoDB))
                    .addComponent(jBAddDT))
                .addContainerGap(451, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        // jLabel_UserName.setText(string);
       // jLabel_UserProfile.setText(string);
       String requetteSQL_SELECT_ALL_PROJECT_NAME = "select project_name from tproject;";
       String requetteSQL_SELECT_ALL_ECU_NAME = "select ecu_name from tecu;";
       

       //// Initiation de la combo Project 
       try {
           stmt = aqswDBCON.getCon().createStatement();
           resultRequete_project = stmt.executeQuery(requetteSQL_SELECT_ALL_PROJECT_NAME);
            while(resultRequete_project.next())
                {
                /** on insere dans la ComboBox */
                jComboBox_ProjectList_FromDB.addItem(resultRequete_project.getString("project_name"));
                } 
            resultRequete_project.close();
            stmt.close();
            } 
       catch (SQLException ex) 
            {
            System.out.println(ex);
            } 
    
       // Initiation de la combo ECU
       try {
           stmt = aqswDBCON.getCon().createStatement();
           resultRequete_ecu = stmt.executeQuery(requetteSQL_SELECT_ALL_ECU_NAME);
            while(resultRequete_ecu.next())
                {
                /** on insere dans la ComboBox */
                jComboBoxECUName_fromDB.addItem(resultRequete_ecu.getString("ecu_name"));
                } 
            stmt.close();
            resultRequete_ecu.close();
            } 
       catch (SQLException ex) 
            {
            JOptionPane.showConfirmDialog(null,
                     "TABLE TECU VIDE !", "INFO", JOptionPane.YES_NO_OPTION);    
            System.out.println(ex);
            } 
    }//GEN-LAST:event_formWindowActivated
    
    private void displayECUDataInTable()
    {
        
        DefaultTableModel model = (DefaultTableModel) jTableECUADDED.getModel();
        //model.setRowCount(0);
        Object[] row = new Object[7];
        
        
            row[0] = jTDTName.getText();
            row[1] = jComboBoxECUName_fromDB.getSelectedItem().toString();
            row[2] = jTECUFullName.getText();
            row[3] = jTSupplierName.getText();
            row[4] = jComboBoxASILLevel.getSelectedItem().toString();
            row[5] = jTECUDomaine.getText();
            row[6] = jTBOXType.getText();
            model.addRow(row);
        
    }
    private void jBAddECUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddECUActionPerformed
        
        displayECUDataInTable();
    }//GEN-LAST:event_jBAddECUActionPerformed

    public int get_DT_ID()
    {   
        int dtid = 0;
        String requetSQL_GET_DET_ID = "SELECT dt_id FROM tdeft WHERE dt_name = '"+jTDTName.getText()+"'";    
        System.out.println("SELECT * FROM tdeft WHERE dt_name = "+ jTDTName.getText());
        try
        {
            stmt = aqswDBCON.getCon().createStatement();
            resultRequete_dt = stmt.executeQuery(requetSQL_GET_DET_ID);
            while(resultRequete_dt.next())
            {
                dtid = resultRequete_dt.getInt("dt_id");
                System.out.println("apres requetSQL_GET_DET_ID ");
                System.out.println("1- ID de la DT : " + dtid);
            }
        resultRequete_dt.close();
        stmt.close();
        }
        
        catch(SQLException ex){
            System.out.println(ex);
        }
        
        return dtid;
    }        
     
    private void jBCommitECUIntoDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCommitECUIntoDBActionPerformed
        
        
        String ecuName = jComboBoxECUName_fromDB.getSelectedItem().toString();
        String ecuFullName = jTECUFullName.getText();
        String ecuSupplierName = jTSupplierName.getText();
        String ecuAsil = jComboBoxASILLevel.getSelectedItem().toString();
        String ecuHWCOCA = jTHWCOCA.getText();
        String ecuSWCOCA = jTSWCOCA.getText();
        String ecuNetw = jTSWNETWORK.getText();
        String ecuSQA = jTSQA.getText();
        String ecuBox = jTBOXType.getText();
        String ecuDomaine = jTECUDomaine.getText();
     
        int defTec_ID = get_DT_ID();
        
        String requetteSQL_INSERT_ECU = "INSERT INTO public.tecu(\n" +
                "ecu_name, ecu_supplier_name, ecu_asil_level, "
                + "ecu_hw_coca, ecu_sw_coca, ecu_network, ecu_sqa, ecu_full_name, "
                + "fk_ecu_deft_id,ecu_domaine, ecu_box_type)\n" +
                "VALUES ('"+ecuName+"', '"+ecuSupplierName+"', '"+ecuAsil+"', "
                + "'"+ecuHWCOCA+"', '"+ecuSWCOCA+"', '"+ecuNetw+"', '"+ecuSQA+"', '"+ecuFullName+"', "
                + "'"+defTec_ID+"', '"+ecuDomaine+"', '"+ecuBox+"');";

        try
        {
            stmt = aqswDBCON.getCon().createStatement();
            stmt.executeUpdate(requetteSQL_INSERT_ECU);
            JOptionPane.showMessageDialog(null, "Requette SQL ajout ECU dans la BDD executee avec succes");
        }
        //stmt.close();
        catch(SQLException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jBCommitECUIntoDBActionPerformed

    private void jComboBox_ProjectList_FromDBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_ProjectList_FromDBMouseClicked
        
        
    }//GEN-LAST:event_jComboBox_ProjectList_FromDBMouseClicked

    private void jComboBox_ProjectList_FromDBMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jComboBox_ProjectList_FromDBMouseWheelMoved
        
    }//GEN-LAST:event_jComboBox_ProjectList_FromDBMouseWheelMoved

    private void jComboBox_ProjectList_FromDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ProjectList_FromDBActionPerformed
    
         
    }//GEN-LAST:event_jComboBox_ProjectList_FromDBActionPerformed

    private void jBShowPrjIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBShowPrjIDActionPerformed
        
        int prj_id = get_Project_ID();
        
       
        jTVehicleID.setText(String.valueOf(prj_id));
        String selectedPrj = jComboBox_ProjectList_FromDB.getSelectedItem().toString();
        String dtName = "DT" + "_" + selectedPrj;
        jTDTName.setText(dtName);
        
    }//GEN-LAST:event_jBShowPrjIDActionPerformed

    private void jBCloseWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCloseWindowActionPerformed
        
        
    }//GEN-LAST:event_jBCloseWindowActionPerformed

    public int get_Project_ID()
    {   
        int prj_id = 0;
        String selectedPrj = jComboBox_ProjectList_FromDB.getSelectedItem().toString();
        System.out.println(selectedPrj);
        String requetSQL_SELECT_PRJ_ID = "SELECT project_id FROM tproject WHERE project_name = '"+selectedPrj+"'";
        
        
        try {
           stmt = aqswDBCON.getCon().createStatement();
           resultRequete_project = stmt.executeQuery(requetSQL_SELECT_PRJ_ID);
            while(resultRequete_project.next())
                {
                /** on insere dans la ComboBox */
                prj_id = resultRequete_project.getInt("project_id");
                } 
            resultRequete_project.close();
            stmt.close();
            } 
       catch (SQLException ex) 
            {
            System.out.println(ex);
            }
        
        return prj_id;
    }
    private void jBAddDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddDTActionPerformed
        
       String selectedPrj = jComboBox_ProjectList_FromDB.getSelectedItem().toString();
       int selected_Prj_id = get_Project_ID();
       
       String requetSQL_INSERT_NEW_DT = "INSERT INTO public.tdeft(dt_name, fk_dt_project_id) VALUES ('"+jTDTName.getText()+"', '"+selected_Prj_id+"');";
       System.out.println("requete a executer : " + requetSQL_INSERT_NEW_DT);
       try
        {
            stmt = aqswDBCON.getCon().createStatement();
            stmt.executeUpdate(requetSQL_INSERT_NEW_DT);
            JOptionPane.showMessageDialog(null, "Requette SQL ajout DT: " + jTDTName.getText()+ " dans la BDD executee avec succes");
            stmt.close();
        }
        //stmt.close();
       
        catch(SQLException ex){
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_jBAddDTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFR_IST_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFR_IST_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFR_IST_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFR_IST_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFR_IST_MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAddDT;
    private javax.swing.JButton jBAddECU;
    private javax.swing.JButton jBCloseWindow;
    private javax.swing.JButton jBCommitECUIntoDB;
    private javax.swing.JButton jBShowPrjID;
    private javax.swing.JComboBox<String> jComboBoxASILLevel;
    private javax.swing.JComboBox<String> jComboBoxECUName_fromDB;
    private javax.swing.JComboBox<String> jComboBox_ProjectList_FromDB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTBOXType;
    private javax.swing.JTextField jTDTName;
    private javax.swing.JTextField jTECUDomaine;
    private javax.swing.JTextField jTECUFullName;
    private javax.swing.JTextField jTHWCOCA;
    private javax.swing.JTextField jTSQA;
    private javax.swing.JTextField jTSWCOCA;
    private javax.swing.JTextField jTSWNETWORK;
    private javax.swing.JTextField jTSupplierName;
    private javax.swing.JTextField jTVehicleID;
    private javax.swing.JTable jTableECUADDED;
    private javax.swing.JToolBar jToolBar_IST_MainFrame;
    // End of variables declaration//GEN-END:variables
}
